#########################################################################
# Title:         Cloudbox: Kernel | Script Tasks                        #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Script | Check for existing 'ubuntu-mainline-kernel.sh'
  stat:
    path: "{{ kernel_script_path }}"
  register: existing_local_script

- name: Script | Tasks for when 'ubuntu-mainline-kernel.sh' exists
  block:

  - name: Script | Calculate hash blob for existing 'ubuntu-mainline-kernel.sh'
    shell: |
      git hash-object {{ kernel_script_path }}
    register: existing_local_script_hash_raw

  - name: Script | Set 'existing_local_script_hash' variable
    set_fact:
      existing_local_script_hash: "{{ existing_local_script_hash_raw.stdout }}"

  - name: Script | Get hash blob for latest 'ubuntu-mainline-kernel.sh'
    uri:
      url: "{{ kernel_script_url }}"
      method: GET
      body_format: json
    register: blob_lookup
    ignore_errors: yes

  - name: Script | Set 'remote_script_hash' variables
    set_fact:
      remote_script_hash: "{{ blob_lookup.json.sha }}"
    when: (blob_lookup is succeeded) and (blob_lookup.json.sha is defined)

  - name: Script | Download and install 'ubuntu-mainline-kernel.sh'
    get_url:
      url:  "{{ kernel_script_url }}"
      dest: "{{ kernel_script_path }}"
      mode: 0775
      owner: root
      group: root
      force: yes
      validate_certs: no
    ignore_errors: yes
    when: (
            (blob_lookup is succeeded)
            and
            (blob_lookup.json.sha is defined)
            and
            (existing_local_script_hash != remote_script_hash)
          )
          or
          (blob_lookup is failed)
          or
          (not existing_local_script.stat.exists)

  when: existing_local_script.stat.exists

- name: Script | Download and install 'ubuntu-mainline-kernel.sh'
  get_url:
    url:  "{{ kernel_script_url }}"
    dest: "{{ kernel_script_path }}"
    mode: 0775
    owner: root
    group: root
    force: yes
    validate_certs: no
  ignore_errors: yes
  when: (not existing_local_script.stat.exists)

- name: Script | Look for '{{ kernel_script_path }}'
  stat:
    path: "{{ kernel_script_path }}"
  register: new_local_script

- name: Script | Validate '{{ kernel_script_path }}'
  shell: |
    head -1 {{ kernel_script_path }} | grep -q '#!/usr/bin/env bash\b'
  register: validate_script
  ignore_errors: yes
  failed_when: validate_script.rc > 1
  when: new_local_script.stat.exists

- name: Script | Import script if validation failed
  copy:
    src: "ubuntu-mainline-kernel.sh"
    dest: "{{ kernel_script_path }}"
    owner: "root"
    group: "root"
    mode: 0775
    force: yes
  when: (not new_local_script.stat.exists)
        or
        ((new_local_script.stat.exists) and (validate_script.rc == 1))
